name: DIGITAL_OCEAN_DEPLOY

on: 
  push:
    branches: [ main ]

  jobs:
    Build:
      runs-on: self-hosted[]

      steps:
      - uses: action/checkout@main
      - name: Create .env
        run: echo "PORT=${{ secret.PORT }}" > .env


      - name: Run build
